name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, arm]
        goarm: [7]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Go dependencies
      run: |
        go env -w GO111MODULE=on
        go mod tidy
        go mod download

    - name: Install UPX and zip
      run: sudo apt-get install -y upx-ucl zip

    - name: Build binary
      run: |
        BUILD_DIR="PandoraHelper-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        mkdir -p "$BUILD_DIR"
        mkdir -p "$BUILD_DIR/data"
        
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="PandoraHelper.exe"
        else
          BINARY_NAME="PandoraHelper"
        fi
        
        if [ "${{ matrix.goarch }}" = "arm" ]; then
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }} go build -ldflags="-s -w" -o "$BUILD_DIR/${BINARY_NAME}" ./cmd/server/main.go
        else
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o "$BUILD_DIR/${BINARY_NAME}" ./cmd/server/main.go
        fi
        
        if [ "${{ matrix.goos }}" != "windows" ] || [ "${{ matrix.goarch }}" != "arm" ]; then
          upx "$BUILD_DIR/${BINARY_NAME}"
        fi
        
        cp -r data/config.json "$BUILD_DIR/data/"

    - name: Compress binaries
      run: |
        ZIP_NAME="PandoraHelper-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.zip"
        BUILD_DIR="PandoraHelper-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        
        # 确保在工作目录下执行压缩
        cd "$GITHUB_WORKSPACE"
        
        # 使用绝对路径进行压缩
        zip -r "$ZIP_NAME" "$BUILD_DIR"
        
        # 验证zip文件
        unzip -t "$ZIP_NAME"
        
        # 如果验证成功，移动到builds目录
        if [ $? -eq 0 ]; then
          mkdir -p builds
          mv "$ZIP_NAME" builds/
        else
          echo "Zip file validation failed"
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PandoraHelper-${{ matrix.goos }}-${{ matrix.goarch }}
        path: builds/*.zip
        retention-days: 1

  commit-builds:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: temp-builds

    - name: Prepare and commit builds
      run: |
        # 配置 Git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # 创建或清理 builds 目录
        mkdir -p builds
        rm -rf builds/*
        
        # 使用find命令找到所有zip文件并复制到builds目录
        find temp-builds -name "*.zip" -exec cp -f {} builds/ \;
        
        # 列出所有复制的文件
        echo "Copied files:"
        ls -la builds/
        
        # 验证所有zip文件
        for zip in builds/*.zip; do
          echo "Validating: $zip"
          if ! unzip -t "$zip" > /dev/null; then
            echo "Error: Invalid zip file: $zip"
            exit 1
          fi
        done
        
        # 强制添加到 Git（忽略 .gitignore）
        git add -f builds/*.zip
        
        # 检查是否有变更
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: update builds for ${{ github.ref_name }}"
          git push
        fi

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: builds

    - name: Validate zip files
      run: |
        for zip in builds/**/*.zip; do
          if ! unzip -t "$zip" > /dev/null; then
            echo "Error: Invalid zip file: $zip"
            exit 1
          fi
        done

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        artifacts: "builds/**/*.zip"
        allowUpdates: true
        draft: false
        prerelease: false
        generateReleaseNotes: true
        body: |
          ## PandoraHelper Release ${{ github.ref_name }}
          
          ### 支持的平台:
          - Windows (amd64)
          - Linux (amd64/arm64/arm)
          - macOS (amd64)
          
          ### 安装说明
          1. 下载对应您系统的压缩包
          2. 解压到任意目录
          3. 运行PandoraHelper可执行文件
          
          ### 注意事项
          - 首次运行请检查data目录下的config.json配置文件
          - 如遇问题请提交issue反馈
